version: '3.0'

expectations:
  population_size: 10000
   
    
actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-12-01 to 2021-02-01 by month" --output-dir=output/measures
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  generate_measures:
      run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output
      needs: [generate_study_population]
      outputs:
        moderately_sensitive:
          measure_csv: output/measure_*.csv

  generate_notebook:
    run: jupyter:latest jupyter nbconvert notebooks/sentinel_measures.ipynb --execute --to html --output-dir=output

    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        notebook: output/sentinel_measures.html 
        
        
        
  