version: '3.0'

expectations:
  population_size: 50000
    # dummy population size must be at least 50000 to ensure the STP analysis can run successfully
    
actions:

  generate_delivery_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_delivery
    outputs:
      highly_sensitive:
        cohort: output/input_delivery.csv

  generate_eligibility_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_eligibility
    outputs:
      highly_sensitive:
        cohort: output/input_eligibility.csv

  generate_notebook:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/population_characteristics.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400

    needs: [generate_delivery_cohort]
    outputs:
      moderately_sensitive:
        notebook: output/population_characteristics.html 
        figures: interim-outputs/figures/*
        tables: interim-outputs/tables/*
        csvs: machine_readable_outputs/*/* # two possible subfolders
        text: interim-outputs/text/*
        
        
  generate_report:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/opensafely_vaccine_report_overall.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input

    needs: [generate_delivery_cohort, generate_notebook]
    outputs:
      moderately_sensitive:
        notebook: output/opensafely_vaccine_report_overall.html 
        csvs: machine_readable_outputs/table_csvs/*
        
        
  generate_notebook_stp:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/stp_breakdown.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400

    needs: [generate_delivery_cohort]
    outputs:
      moderately_sensitive:
        notebook: output/stp_breakdown.html
        figures: interim-outputs/stp/figures/*/*
        tables: interim-outputs/stp/tables/*
        text: interim-outputs/stp/text/*
        
        
  generate_report_stp:
    run: jupyter:latest jupyter nbconvert /workspace/notebooks/opensafely_vaccine_report_stp.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input

    needs: [generate_delivery_cohort, generate_notebook_stp]
    outputs:
      moderately_sensitive:
        notebook: output/opensafely_vaccine_report_stp.html 
        
        
        
